name: Deploy

on: 
  push:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Build
        run: go build -o app cmd/main.go # TODO: build cmd/prod/main.go

      - name: Test
        run: go test -v ./...

      - name: Create .env file
        run: |
          touch .env
          echo MY_NAME=${{ secrets.MY_NAME }} >> .env

      - name: Publish to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "app,.env,migrations/*"
          target: /home/app

      - name: Start the service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            migrate -path migrations -database postgres://app:password@localhost:5432/app up
            chmod 660 /home/app/.env
            sudo systemctl restart app